
USE DATABASE MYDB;
USE SCHEMA PUBLIC;

CREATE OR REPLACE TABLE CUSTOMER (
    CUSTOMER_ID INT AUTOINCREMENT PRIMARY KEY,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    PHONE STRING,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

